### PR TITLE
v 1.0 features / fixes

### PR DESCRIPTION
**Pull request by andrewpbray**
A bundle of features, fixes, and documentation in advance of the Closeread Contest.

### CODE REVIEW

**Comment by jimjam-slam** [comment]
I can't see the conflicts on my phone, but if you're out of steam I can get into this merge in about 90 minutes!

**Comment by andrewpbray** [comment]
Fixed! Looks like it'll give us one last look at preview.closeread.dev before approving and merging.

**Comment by andrewpbray** [comment]
Looks like sticky blocks shows up in Demos. Did your tests branch not make it into `dev`?

**Comment by jimjam-slam** [comment]
Ah - it looks like I moved one test but not the other 🤦🏻  Will move the other now!

**Comment by jimjam-slam** [comment]
Both tests now in `/tests`! Note that I renamed the `sticky-blocks` test to `figure-environments`  (to distinguish it from `sticky-block-types`), and`/tests` isn't in the nav bar (though you can still navigate to the address manually).

Finally, I ran `sass closeread.scss closeread.css` one last time to iron out any feature or bugfix merge problems.

**Comment by andrewpbray** [comment]
I'm headed to bed but feel free to merge / release!

**Comment by jimjam-slam** [comment]
Will do - sorry to have you up so late!

**Review by jimjam-slam — APPROVED** [review]
Merges cleanly locally and appears to render and preview as it does on main! Let's roll!

**Pull request merged**
